In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sn

In [3]:
df=pd.read_csv('Salary_Data.csv')

In [5]:
df.head(5)

YearsExperience   Age  Salary
0              1.1  21.0   39343
1              1.3  21.5   46205
2              1.5  21.7   37731
3              2.0  22.0   43525
4              2.2  22.2   39891

In [7]:
df.isnull().sum()

YearsExperience    0
Age                0
Salary             0
dtype: int64

In [9]:
df.tail(5)

YearsExperience   Age  Salary
25              9.0  34.0  105582
26              9.5  35.0  116969
27              9.6  36.0  112635
28             10.3  37.0  122391
29             10.5  38.0  121872

In [13]:
df.duplicated().sum()

0

In [15]:
df.shape

(30, 3)

In [17]:
x=df.drop('Salary',axis=1)
y=df['Salary']

In [19]:
x.columns

Index(['YearsExperience', 'Age'], dtype='object')

In [21]:
y.name

'Salary'

In [23]:
from sklearn.preprocessing import StandardScaler

In [25]:
sc=StandardScaler()
sc.fit(x)


StandardScaler()

In [29]:
df[['YearsExperience','Age']]=sc.transform(x)

In [31]:
x.head(3)

YearsExperience   Age
0              1.1  21.0
1              1.3  21.5
2              1.5  21.7

In [33]:
df.head(5)

YearsExperience       Age  Salary
0        -1.510053 -1.225076   39343
1        -1.438373 -1.126544   46205
2        -1.366693 -1.087131   37731
3        -1.187494 -1.028012   43525
4        -1.115814 -0.988600   39891

In [36]:
from sklearn.model_selection import train_test_split

In [308]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=41)

In [368]:
print(x_test.shape)
print(x_train.shape)
print(y_train.shape)
print(y_test.shape)

(9, 2)
(21, 2)
(21,)
(9,)


In [370]:
from sklearn.neighbors import KNeighborsRegressor

In [372]:
knn=KNeighborsRegressor(n_neighbors=4)
knn.fit(x_train,y_train)

KNeighborsRegressor(n_neighbors=4)

In [374]:
knn.score(x_train,y_train)*100

96.55403594878831

In [376]:
knn.score(x_test,y_test)*100

97.81430309178778

In [378]:
knn.predict([[9.0,34.0]])

C:\Users\mishr\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but KNeighborsRegressor was fitted with feature names
  warnings.warn(


array([108332.75])

In [380]:
# 9.0	34.0	105582

In [357]:
knn.predict([[-1.438373,-1.126544]])

C:\Users\mishr\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but KNeighborsRegressor was fitted with feature names
  warnings.warn(


array([41701.])

In [359]:
# -1.438373	-1.126544	46205

In [274]:
for i in range(1,10):
    kn1=KNeighborsRegressor(n_neighbors=i)
    kn1.fit(x_train,y_train)
    print(i,kn1.score(x_train,y_train)*100,kn1.score(x_test,y_test)*100)
    

1 100.0 90.08542457139043
2 98.64483370598232 92.44297738145369
3 98.01610101703676 92.76658314457347
4 97.99623842267373 96.00947532058674
5 96.6163275934304 95.08927993545477
6 95.85954256730011 93.97067573514164
7 93.99702778881789 94.21955968211016
8 92.37933215211814 91.60779887562144
9 90.18654035773041 92.22049622094904


In [366]:
from sklearn.model_selection import cross_val_score

In [384]:
p=cross_val_score(KNeighborsRegressor(),x,y,cv=5)

In [386]:
p.sort()

In [390]:
p*100

array([-632.85538608, -584.88498426, -288.13107472,  -13.30990794,
         69.75728861])